# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SHDcLvMl1XFwyo7zuqSOWfEee2AXdEVo
"""



def Full_name(first_name="first name",last_name='last name'):# create Full name by passing arguments first name and last name
    return first_name+' '+last_name #  conacatinte both first name and last name and return to string
first_name=input("Enter your first name:")# input fuction to take input from user
last_name=input("Enter your last name:")
full_name=Full_name(first_name,last_name)
print(full_name) # print full name

def string_alternative(string):
    o=''
    for i in range(0,len(string)): # iterate loop from 0 to length of string
        if(i%2==0):
            o=o+string[i] # add null string to index of string
    return o

print(string_alternative(full_name)) #print the result

with open('input.txt','r') as ipf:#create input file
    line=ipf.read()# read input file
    word=line.split() # split line into words to perform wordcount
    with open('output.txt','w') as opf:
        for i in word: # Here i have iterated through word variable where the split of words are returned
            opf.write(i+':'+str(word.count(i))+'\n')
opf=open('output.txt','r')
print(opf.read()) #print wordcount

